### ISSUE TITLE
White Light contol

### ISSUE THREAD

**Issue by eliotstocker** [eliotstocker/Light-Controller#10]
Control white only LEDS @mrwhale could you let us know what your are thinking on this one?

**Comment by nagelm** [comment]
@eliotstocker White control is looking good. Only remaining issue I see is that the global white control still doesn't work on the notification/lockscreen widget.

Re: brightness control, @AppLamp-API makes some good points about the transmission delays. What about a hybrid jog control? Something like this:

![image](https://cloud.githubusercontent.com/assets/10207686/5658455/cdf3c094-9766-11e4-83a0-3aeef38768b0.png)

Where the dial springs back to the middle resting position after a user interaction. This way you can make a relative brightness adjustment with a single interaction.

**Comment by dudeofawesome** [comment]
I haven't really been following along on progress, but a thought I had to
semi fix the relativity of brightness would be to store the last known
brightness value and offer a calibrate button that sets the light to
maximum brightness by calling brightness up 8(?) times.

**Comment by eliotstocker** [comment]
I think im going to go along with what @AppLamp-API said, a jog dial works the best in this situation. as you can have multiple controllers it can get very confusing if trying to keep a track of the current position.

i have already started to implement this a little and will try and have something done for this weekend. then we should be looking forward to a new release

**Comment by AppLamp-API** [comment]
Hi Eliot,
Nice to hear.
Make sure it has an attractive ticking sound when you rotate it ;)
The original remote has 14 clicks per 360 degrees, or 25 degrees per click
but for the APP I think it is better to have more jog clicks, like 15 
degrees per jog "click" or 24 clicks per 360 deg round.
Cheers!
Stijn

**Comment by eliotstocker** [comment]
OK Guys heres the latest beta:
https://www.dropbox.com/s/5qac7w7qibp92na/LC1-debug.apk?dl=0

i have now added two jog dials for the white light controls.

that should round off most of the features, so if we're all happy with this, then we can squash the bugs and go for a release :)

**Comment by mrwhale** [comment]
Looking very nice! 
Bug #1: when I press the dot button to show settings, it crashes:( I'll get a logcat output for you when I get to work and can plug into a pc

**Comment by AppLamp-API** [comment]
I can't run this: "There was a problem parsing the package". Does this 
only works on rooted devices? Stock android 4.4.4 Motorola E (el cheapo 
today :) )
Enabling developer options doesn't seem to make a diff. That is why I 
compiled the App myself last time...
Any hints?
Cheers,
Stijn

**Comment by nagelm** [comment]
Looks great, I'll test when I'm home.

**Comment by AppLamp-API** [comment]
Ok, mine works now. It had to do with my downloader that place some UTF bomb wrong I guess. Now I was able to install. Findings:
- Great TAB animation!
- Crashing on leaving the settings menu, either by Android back arrow or by GUI arrow.
- Jog animates but does not functions ( no result on my bulbs ), not for dimming, not for color temperature.
- All other white buttons work well: full, night, On/Off
- RGBW dimmer slider misses regularly last state if you slide too fast: 100% up should alsway be 100% light, it has to do with wifi box dropping commands. There should be a repeat of the last dimming command after say 150 or 200 ms after the slider starts idling on user input as a closing package.

Good work!

**Comment by AppLamp-API** [comment]
and I'd love to see a "DETECT" button at he IP settings, to upodate broadcast settings if you switch networks.

**Comment by mrwhale** [comment]
Looking awesome! Having the same issue as @AppLamp-API, point number 4. The brightness warm/coolness commands don't do anything

Nevermind, just looking at your commits, you say you haven't implemented the actual commands yet

**Comment by eliotstocker** [comment]
Hmm should be working :(

this is the commit where i wired it up, can someone check my byte messages are ok for bright/warmth up and down?

https://github.com/eliotstocker/Light-Controller/commit/26f7a12bf96759c3522407d70a8c86dd3e13ae61

**Comment by AppLamp-API** [comment]
Code looks good.
Doublechecked.

brightUp = function(){ return [0x3c,0x00,0x55] };
(60,0,85)

brightDown = function(){ return [0x34,0x00,0x55] };
(52,0,85)

warmer = function(){ return [0x3E,0x00,0x55] };
(62,0,85)

cooler = function(){ return [0x3F,0x00,0x55] };
(63,0,85)

**Comment by AppLamp-API** [comment]
Make sure you send the ON command for the zone or ALL _*once*_ before 
using the cooler / warmer and bright up / down.
this will first activate the right bulb.

WhiteCmd.prototype.on  =  function(zone ~~INDEX ZERO TO THREE~~){
                                                 return  [
							 [  0x45,0x38,0x3D,0x37,0x32][zone]
                                                            ,0x00
							   ,  0x55
                                                          ];
                          };

**Comment by eliotstocker** [comment]
OK i think i fixed the issue now, was my bad i was re-centering the control before measuring the value.
should have fixed the preference issue too i think, accidentally added a couple of preferences with the same id, added a link to everyones github too :)

new beta:
https://www.dropbox.com/s/5qac7w7qibp92na/LC1-debug.apk?dl=0

**Comment by AppLamp-API** [comment]
Checked your last beta and the crash on prefs seems to be gone.
The white lights bright / color temperature still don't work.
Where are you located? Please send me your full adress details to 
sales@applamp.nl and I'll send you a few bulbs to test with.

Cheers De Ryck,
Stijn AppLamp
www.applamp.nl
www.wifiledlamp.com

**Comment by nagelm** [comment]
With the latest beta the brightness control is working fine for me, no luck with colour temp though.

All white lockscreen/notification bar control is not working. It seems to control the all colour zone instead of the all white

**Comment by myntath** [comment]
Yeah finding the same as nagelm. Warmth coolness control isn't working.

The widgets often stop working. What I have noticed about the widgets is that when I place two (a white and colour) on the same screen all looks ok but after a few switches one widget will switch to become the other type so I will have two colour or two white. The names of the zones change making it clear the widget has changed types.

Otherwise the app is great and I'm using it daily. I noticed that there is no night mode setting for the rgb globes yet, would love to see that added to further increase options.

**Comment by AppLamp-API** [comment]
There is no nightmode available for RGBW bulbs.
The nightmodfe is implemented only in (the hardware) of the White bulbs.

**Comment by myntath** [comment]
I think there might be nightmode for RGBW but I hadn't seen anything until fairly recently, check out the following from http://www.limitlessled.com/dev/

"November 2014: how to send Nightmode to RGBW lights. send a second Off command 100 ms later. the second off command is a long press.. and it is command |= 0×80. for example 46 XOR 80 = C6 > So send 460055 Wait 100ms Then send C60055. that is hex commands 46 00 55 and C6 00 55."

I think at the time I tested it out and it worked. Will test it out later today when I get home to see if it is possible.

**Comment by LimitlessLED** [comment]
HOWTO: Send Nightmode to LimitlessLED RGBW lights.  www.limitlessled.com/dev 

 

send 460055 Wait 100ms Then send C60055. (they are 3 hex bytes: 46 00 55 and C6 00 55)

 

technical implementation details:

to send a long press command, the format is always, send a second Off command 100 ms later. the second off command is a long press.. and the long press command is always XORed  ( 0x46 |= 0×80 )  for example 46 XOR 80 = C6  means the long press command is send  C6 

 

press off = 0x46

longpress off = 0x46 |= 0x80   (result is 0xC6)

 

Regards,
Hamish.

-LimitlessLED.

www.limitlessled.com

**Comment by myntath** [comment]
Yeah my bulbs definitely support it, even works by using the official app by pressing off then long press off. There doesn't seem to be any colour control or brightness control while in night mode.

**Comment by AppLamp-API** [comment]
Doublechecked.
Nightmode indeed it works on RGBW bulbs.
Even only longpressing only (without first single OFF press) works. 
Didn't know that.

**Comment by eliotstocker** [comment]
Hmm odd, mine dont appear to do it, perhapse i have old bulbs. ill add a button either way :)

**Comment by LimitlessLED** [comment]
Longpressing the remote or app, sends both commands for it..

 

Or were you blasting udp to just force the longpress command only?  Otherwise how can you skip the first single OFF press, when the app and remote does it for you.

 

Regards,

Hamish.

-LimitlessLED

www.limitlessled.com

**Comment by eliotstocker** [comment]
Hi Guys, today i received a lovely package from @AppLamp-API so with that i have now gotten the brightness and warmth jog dials working perfectly :)

here is the latest beta:
https://www.dropbox.com/s/5qac7w7qibp92na/LC1-debug.apk?dl=0

so yeah, massive thanks to @AppLamp-API, you should all go buy some bulbs from him at:
http://www.applamp.nl/ :)

**Comment by eliotstocker** [comment]
I have updated that APK with some more fixes for widgets etc, i think i have pretty much all of the bugs worked out now :) and i made a curry too! good evening

**Comment by mrwhale** [comment]
Awesome stuff:) downloading and testing!  Amazing work too @AppLamp-API. You ship to Australia :P ?

**Comment by eliotstocker** [comment]
My girlfriend found that she got a few NPEs from the WidgetProvider, so i have updated the APK again, let me know if you find any more issues

**Comment by eliotstocker** [comment]
i have added a new branch with a nav drawer, as i find the tabs to be a little difficult when there are 10 items, what do you guys think?

**Comment by wjbeckett** [comment]
Hi Elliot,
Fantastic idea. This is what I was mentioning a while ago as a design
tweak. Nice to see it being implemented!

**Comment by nagelm** [comment]
Hey Elliott, great stuff I'll have a play when I'm home. You gonna do a release with white control updates or you wanna get global control/interface ironed out?

Good idea on interface tweaks. Do you have an apk I could take a look at? otherwise I'll check it out at home.

**Comment by AppLamp-API** [comment]
Hi Eliot, thanks for the kind words! Good you have it working now!
I have 2 little tweaks for the GUI:
the brightness and color temperature jogs work great, but on maximum brightness (or coolness / warmth) it always takes two pulls (pull,release,pull) on the jog towards "-8" to get to the absolute minimum brightness ( or warmth / coolness) of the bulb. I don't know how many command you fire, but without a miss / package drop on the wifi bridge it should take 10 "+plus" or "-minus" command fires to get to a minimum or a maximum, starting from the outer dim / color temperature position. So maybe better make it "+10 / -10", so a user can max out a state in one "pull. 
Or if the user pulls and holds the jog slider in an outer position, you could fire (after a small timeout) an additional 3 + or - commands to max out the bulb state for that slider function. 

I also would make the jog dots a tad bigger, because on smaller screens you easily start dragging the zone page instead of the jog, if you don't center your finger well on the jog-dot.

Just a little GUI thing: the word "Warmth" is cutoff on the bottom (bottom out of frame bounds) and loses 1/4th of it's typo pixels. The word "Warmth" could be replace by "Color Temperature", if you like it.

**Comment by eliotstocker** [comment]
Hey guys glad its working, i have a few more small bugs to iron out before a release but i think were headed to towards the full release now :)

@wjbeckett yeah thought you might like that haha :) heres an APK:
https://www.dropbox.com/s/9swcgxsf1rnhzqr/LC1-navbar-debug.apk?dl=0
i think in the final version i might make it an option to have one or the other as that should be simple enough. (as the tabs still make sense if you disable color or white zones).

@AppLamp-API yeah ill change the jog to have 20 steps rather than 16. that should be simple enough, and making the dot bigger should be fine too :) could you show me a screenshot of the text clipping?

can we get a bit of a poll going here? Warmth or Color Temperature?

**Comment by mrwhale** [comment]
Yeah color temperature makes more sense, covers both warmth/coolness

**Comment by wjbeckett** [comment]
Seems to crash for me when pressing the overflow menu button (3 dots).

Not sure if anything is meant to be in there but just one small thing I
noted.

**Comment by eliotstocker** [comment]
Right heres a new beta:
https://www.dropbox.com/s/5qac7w7qibp92na/LC1-debug.apk?dl=0

the new Nav Drawer is now the default navigation type, however you can change back to tabs in the settings if you prefer that :) (overflow menu will only show when tabs are enabled, settings has moved into the drawer now when enabled)

i have tweaked the white control layout a bit to hopefully fix a few issues @AppLamp-API i have switched the number of jumps to 10 each way now. and i have changed the wording to "color temperature" also.

right if we find the bugs are gone then im going to close this issue

**Comment by mrwhale** [comment]
Nice stuff @eliotstocker! that navigation draw looks awesome! Will give it a test tonight

**Comment by mrwhale** [comment]
Just had a test, looking really good ! Pretty sure I'm just nit picking now, but when I have a white zone in night mode, and then press night mode again, it goes to full brightness then back down to night mode. So brightens up, before going back into night mode. I'll take a look at the code, to see if it's a bug or was designed that way. Awesome stuff though :) I'll open a new issue/ or maybe just send you a PM on hangouts or something, but I just merged this latest white branch into mine, and am getting NPEs when installing/running for the first time

**Comment by mrwhale** [comment]
Okay, I just tested the same thing with my bash script that does light controls. It does the same thing when sending night mode to the lights when it's already in night mode. However, mine didn't go as bright as this app does. Maybe timing? Mine has minimal timing when sending commands so I guess that could be it. Anyways, just something I thought I'd share. Obviously not a bug in the code though

**Comment by eliotstocker** [comment]
Right seems this is all working lovely, so im going to close this and put out a new release :)
feel free to open a new issue for any related stuff.
great work all!
