### ISSUE TITLE
Crash on opening settings v1.8b

### ISSUE THREAD

**Issue by mrwhale** [eliotstocker/Light-Controller#75]
So here is a snippet on what happens when trying to open settings, on the latest beta

```
10-28 11:37:03.408 30768 30768 D AndroidRuntime: Shutting down VM
10-28 11:37:03.410 30768 30768 E AndroidRuntime: FATAL EXCEPTION: main
10-28 11:37:03.410 30768 30768 E AndroidRuntime: Process: tv.piratemedia.lightcontroler, PID: 30768
10-28 11:37:03.410 30768 30768 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{tv.piratemedia.lightcontroler/tv.piratemedia.lightcontroler.controlPreferences}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String tv.piratemedia.lightcontroler.api.Provider.Name' on a null object reference
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.app.ActivityThread.-wrap12(ActivityThread.java)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:154)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6077)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
10-28 11:37:03.410 30768 30768 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String tv.piratemedia.lightcontroler.api.Provider.Name' on a null object reference
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at tv.piratemedia.lightcontroler.controlPreferences$PrefsFragment.onCreate(controlPreferences.java:94)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.app.Fragment.performCreate(Fragment.java:2335)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.app.BackStackRecord.setLastIn(BackStackRecord.java:857)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.app.BackStackRecord.calculateFragments(BackStackRecord.java:880)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.app.BackStackRecord.run(BackStackRecord.java:727)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.app.FragmentController.execPendingActions(FragmentController.java:371)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.app.Activity.performStart(Activity.java:6680)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609)
10-28 11:37:03.410 30768 30768 E AndroidRuntime:    ... 9 more
10-28 11:37:03.415   849  6925 W ActivityManager:   Force finishing activity tv.piratemedia.lightcontroler/.controlPreferences
```

**Comment by eliotstocker** [comment]
resolved in beta3 being pushed to the play store now

**Comment by mrwhale** [comment]
Hey Eliot, just reopening this one. I'm on the latest beta release (pushed via play store) but still getting crashing when opening settings. Tried reinstalling and all that jazz

**Comment by eliotstocker** [comment]
hmm wierd, can you do me a logcat?
still crashing in the same place?

**Comment by mrwhale** [comment]
Okay so install of latest beta 1.8.B4 this isn't happening anymore

**Comment by eliotstocker** [comment]
Great :)

Closing again, please let me know if the issue reappears
